site_name: FLaP
repo_url: https://github.com/fchauvel/flap
docs_dir: docs
pages:
 - "Home": index.md
 - "User Guide":
   - installation.md
   - example.md
 - Contributing: contributing.md
theme: flatly