site_name: FLaP
docs_dir: sources
repo_url: https://github.com/fchauvel/flap
pages:
 - "Home": home.md
 - "User Guide":
   - installation.md
   - example.md
 - Contributing: contributing.md
theme: flatly